### ISSUE TITLE
Unable to deploy ARM template on line 36 of LabDeploy.ps1

### ISSUE THREAD

**Issue by patpicos** [kromerm/adflab#1]
The primary error seems to be that the ARM template doesnt recognize the parameters event thought the JSON file is valid.

**Main Error:**
...
New-AzureRmResourceGroupDeployment : A parameter cannot be found that matches parameter name 'labNamePrefix'.
At C:\adflab\Deployment\LabDeploy.ps1:36 char:113
+ ... e $resourceGroupName -TemplateFile LabARM.json -labNamePrefix $labNam ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzureRmResourceGroupDeployment], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGr 
   oupDeploymentCmdlet
...

**Configuration:**
$dir = "C:\adflab"                          #Working directory of where your LabDeploy.ps1 file is located
$resourceGroupName = "adflab-test"               #Name of Azure resource group to deploy the lab resrouces to, will create if it does not exist
$location = "East US 2"                     #Geo location of resource group, resources will use this as well
$labNamePrefix = "adflab"                   #prefix to append on to unique names such as SQLServer and Storage account
$sqlUsername = "labadmin"                   #SqlServer admin account
$sqlPassword = "*******"                  #SqlServer admin password
$logicAppEmail = "ppicard@picardconsulting.ca" #O365 Account to send emails for lab
$subscriptionName = "Development" #Name of subscription to use for deployment

Full Log Attached as comment

**Comment by patpicos** [comment]
[Deploy Log.txt](https://github.com/kromerm/adflab/files/1678865/Deploy.Log.txt)

**Comment by patpicos** [comment]
Fixed by changing path to
C:\adflab\Deployment

$dir = "C:\adflab\Deployment"

**Comment by joshuha** [comment]
Since most people will probably extract the lab from a Zip containing the entire project I did just add a \Deployment path to the end of the $dir to make that more apparent.
