### ISSUE TITLE
Changing protection level error in Module 2

### ISSUE THREAD

**Issue by jcsinclair** [kromerm/adflab#10]
When I try to deploy the ADFLab.isproj file in Module 2 I receive the following error:
Changing protection level - Value does not fall within expected range. (Microsoft.SqlServer.ManagedDTS)

**Comment by joshuha** [comment]
@jcsinclair Do you have the Azure SSIS Feature Pack installed from wherever you are doing the deployment from?

**Comment by jcsinclair** [comment]
That fixed it.  Thanks.  Missed that in the prerequisites.
