### ISSUE TITLE
LAB01 - AirlinePerformance-OLTP bacpac is corrupt

### ISSUE THREAD

**Issue by iaclarke** [kromerm/adflab#12]
Hi

I might be doing something wrong here because it looks like other people have got past this point. The AirlinePerformance-OLTP database doesn't restore successfully. It returns a corrupt file error. I got this through both the Powershell script and by attempting to manually import the database from the bacpac file.

The shell of the database is created, with no user defined objects.

![image](https://user-images.githubusercontent.com/36425582/36124288-6a90b0cc-1047-11e8-965e-3082f411f2f2.png)
![image](https://user-images.githubusercontent.com/36425582/36124370-aa793542-1047-11e8-827c-a50882546aec.png)

Thanks
Ian

**Comment by kromerm** [comment]
The complete BACPAC for the OLTP is getting corrupted by the Github LFS. I removed the full bacpac and kept the shredded compressed files. For now, you can download the individual files and put them back together with 7zip. I just tested it and it works. I'm working on an LFS resolution so you can just download the full bacpac as well.

**Comment by iaclarke** [comment]
This worked. Thanks 👍
