### ISSUE TITLE
LAB03 References to LAB01 VSTS Git

### ISSUE THREAD

**Issue by lnewportmsft** [kromerm/adflab#13]
Howdy, running through these.  The LAB03 module starts out with setting up a code repository (VSTS Git) and references the repository set up in LAB01, but LAB01 does not have repository setup step.

"We will be using the Azure Data Factory we created in Lab 01 called adflab-adf. We also will use a VSTS Git (or Github) account to version code in the GUI pipeline tool. This was also setup in Lab01 but we will show how to connect it."

**Comment by joshuha** [comment]
Yeah this is something we need to update in the documentation not to refer to lab module 1 and instead link to an MS Article on setting up a VSTS repo. Will try and get that updated soon.

**Comment by joshuha** [comment]
Updated the module to refer to a MS VSTS Git tutorial as well as an additional line to stress that the section is optional and can skip to Part 2 if you want to use ADF to manage your code.
