### ISSUE TITLE
CreateAzureDW.sql not working

### ISSUE THREAD

**Issue by skalingclouds** [kromerm/adflab#14]
When executing the build script in powershell, it errors at the SQL DW  Schema build. Error from Powershell below

"
Invoke-Sqlcmd : Parse error at line: 9, column: 1: Incorrect syntax near 'DimDate'.
At C:\Users\chris\azure\adflab\Deployment\LabDeploy.ps1:100 char:1
 Invoke-Sqlcmd -inputFile "CreateAzureDW.sql" -ServerInstance "$sqlSer ...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlPowerShellSqlExecutionException
FullyQualifiedErrorId : SqlError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand

Invoke-Sqlcmd : Parse error at line: 110, column: 1: Incorrect syntax near 'END'.
At C:\Users\chris\azure\adflab\Deployment\LabDeploy.ps1:100 char:1
Invoke-Sqlcmd -inputFile "CreateAzureDW.sql" -ServerInstance "$sqlSer ...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlPowerShellSqlExecutionException
FullyQualifiedErrorId : SqlError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand"
"

Tried executing in SQL, first few lines of error are here: 

"Msg 15151, Level 16, State 1, Line 4
Cannot alter the role 'largerc', because it does not exist or you do not have permission.
Msg 102, Level 15, State 1, Line 32
Incorrect syntax near 'DISTRIBUTION'.
Msg 102, Level 15, State 1, Line 52
Incorrect syntax near 'DISTRIBUTION'. "

**Comment by kromerm** [comment]
Checking to see if the previously reported fixes address this
