### ISSUE TITLE
Lab 2 - SSIS Package Deploy Failed

### ISSUE THREAD

**Issue by patpicos** [kromerm/adflab#5]
Step 9 - Returns error:
TITLE: SQL Server Integration Services
------------------------------
Warning: Failed to decrypt an encrypted XML node. Verify that the project was created by the same user. Project load will attempt to continue without the encrypted information.

Warning: Failed to decrypt sensitive data in project with a user key. You may not be the user who encrypted this project, or you are not using the same machine that was used to save the project. If the sensitive data is a parameter value, the value may be required to run the package on the Integration Services server.

Step 12:
TITLE: SQL Server Integration Services
------------------------------
Value does not fall within the expected range. (Microsoft.SqlServer.ManagedDTS)

This was flagged during the validation step.
Error:

Then click back, then Next, then next then Deploy

TITLE: SQL Server Integration Services
------------------------------
Unable to create the type with the name 'AzureStorage'. (Microsoft.SqlServer.ManagedDTS)

**Comment by joshuha** [comment]
Can you try downloading the Azure SSIS Feature pack for SQL Server 2017 to the machine you are running the ISPAC from? https://www.microsoft.com/en-us/download/details.aspx?id=54798 If that works I have a version of the document that will call that out as a requirement.

**Comment by kromerm** [comment]
We have a fix for the validation errors, will update repo shortly
