### ISSUE TITLE
Lab 3 - Creation of VSTS Git Project

### ISSUE THREAD

**Issue by patpicos** [kromerm/adflab#6]
The document refers to Lab 1 instructions that are non-existent

_In Lab 01 we setup a VSTS Git project and will link it here. Github can also be used._

**Comment by kromerm** [comment]
Which document / lab manual is that?

**Comment by kromerm** [comment]
Never mind, found it

**Comment by joshuha** [comment]
Mark,
Should we just change the documentation (since this section is optional) to state that if you have a VSTS Git repository here is how you connect it but leave the creation of a VSTS Git outside the scope of the lab?

**Comment by patpicos** [comment]
pointing to a MS link on how to setup a VSTS Git would be sufficient. I think it is valuable from a completeness perspective
