### ISSUE TITLE
Lab 3 - FAAMaster Path step 21

### ISSUE THREAD

**Issue by patpicos** [kromerm/adflab#7]
The path should read input/FAAMaster (to allow pulling the schema)

**Comment by patpicos** [comment]
[LAB03 - Rebuilding the Extract and Load with ADF.docx](https://github.com/kromerm/adflab/files/1679298/LAB03.-.Rebuilding.the.Extract.and.Load.with.ADF.docx)

**Comment by patpicos** [comment]
if that is not the case, when i try to click "Get Schema" the schema from the source does not carry over. (step 20-23)

error:
Loading Error
"Error when processing request: The required Blob is missing. ContainerName: https://adflabstorage7nuut.blob.core.windows.net/input, ContainerExist: True, BlobPrefix: FAAmaster.txt, BlobCount: 0. activityId: 731581cb-60a1-4c8e-bd20-7854d1f0061b"

**Comment by patpicos** [comment]
Doing a test run, the following error:
{
    "errorCode": "2200",
    "message": "ErrorCode=UserErrorSourceDataContainsMoreColumnsThanDefined,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Error found when processing &apos;Csv/Tsv Format Text&apos; source &apos;MASTER.txt&apos; with row number 401059: found more columns than expected column count: 34.,Source=Microsoft.DataTransfer.Common,'",
    "failureType": "UserError",
    "target": "S3 to Azure blob"
}

**Comment by joshuha** [comment]
Fixed the instructions to mention drilling down into the folder. Technically when copying to a file you don't need a schema on the sink side but we put that in there to make it more consistent. You may not always have a file on the sink in a lot of cases.

Looks like a step was messed for the quote character on the source side. Some rows do have commas in the text and those use " as a quote character. Added that in the documentation as well.
