### ISSUE TITLE
Lab 5 - WASB Paths require updates

### ISSUE THREAD

**Issue by patpicos** [kromerm/adflab#8]
The documentation should ask the developer to update the FAAMerge.hql hive script to reflect the automatically generated storage account name

Mine was adflabstorage7nuut for example.

This is required 3 times in the HQL.

Also, hard coding of storage accounts in HQL makes the script not portable between environments.

**Comment by kromerm** [comment]
Good point ... we'll add replacement vars in the script and document those actions required

**Comment by joshuha** [comment]
Since you can edit this right in the GUI with Add/Edit script I added steps and screenshot for that in Lab Module 5.
