### ISSUE TITLE
Lab 5 - Running HiveQL Pipeline fails

### ISSUE THREAD

**Issue by patpicos** [kromerm/adflab#9]
I followed the instructions to setup the ondemand cluster and put the details about the HQL script to execute.

When doing a test run, I get the following error:

{
    "errorCode": "105",
    "message": "Object reference not set to an instance of an object.",
    "failureType": "SystemError",
    "target": "Run FAA Hive Merge"
}

Are there ways to troubleshoot pipelines in ADF? every error is pretty obscure.

# JSON Code for pipeline:
{
    "name": "Merge FAA Files",
    "properties": {
        "activities": [
            {
                "name": "Run FAA Hive Merge",
                "type": "HDInsightHive",
                "dependsOn": [],
                "policy": {
                    "timeout": "7.00:00:00",
                    "retry": 0,
                    "retryIntervalInSeconds": 20
                },
                "typeProperties": {
                    "scriptPath": "input/FAAMerge.hql",
                    "arguments": [],
                    "defines": {},
                    "scriptLinkedService": {
                        "referenceName": "AzureStorage-Staging",
                        "type": "LinkedServiceReference"
                    }
                },
                "linkedServiceName": {
                    "referenceName": "HDI-ADFLab",
                    "type": "LinkedServiceReference"
                }
            }
        ]
    }
}

# JSON Code for Activity
{
    "name": "Run FAA Hive Merge",
    "type": "HDInsightHive",
    "dependsOn": [],
    "policy": {
        "timeout": "7.00:00:00",
        "retry": 0,
        "retryIntervalInSeconds": 20
    },
    "typeProperties": {
        "scriptPath": "input/FAAMerge.hql",
        "arguments": [],
        "defines": {},
        "scriptLinkedService": {
            "referenceName": "AzureStorage-Staging",
            "type": "LinkedServiceReference"
        }
    },
    "linkedServiceName": {
        "referenceName": "HDI-ADFLab",
        "type": "LinkedServiceReference"
    }
}

**Comment by TT138** [comment]
I am having the exact same issue

**Comment by joshuha** [comment]
Is this still true after the update to Lab Module 5 to change the output location in the Hive script?

**Comment by TT138** [comment]
I might have had the old version. I've downloaded the current script and it works fine. Thanks!
